language: ruby
rvm:
  - 2.1.0
  - 2.0.0
services: postgresql
before_script:
  - psql -c 'create database sallyapi_test;' -U postgres
  - cp config/database.yml.example config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
